export const ADD_QUESTION = "ADD_QUESTION";
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const CHANGE_LIST_TYPE = "CHANGE_LIST_TYPE";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const SEE_RESULT = "SEE_RESULT";
export const REFRESH_UPDATES = "REFRESH_UPDATES";
export const LOGIN = "LOGIN";
export const CLEAR_PATH = "CLEAR_PATH";
export const SET_PATH = "SET_PATH";

